// Copyright (c) 2016-2017, XMOS Ltd, All rights reserved
#define AECFREEZEONOFF_DESC         "Adaptive Echo Canceler updates inhibit.\n0 = Adaptation enabled\n1 = Freeze adaptation, filter only"
#define AECNORM_DESC                "Limit on norm of AEC filter coefficients"
#define AECPATHCHANGE_DESC          "AEC Path Change Detection.\n0 = false (no path change detected)\n1 = true (path change detected)"
#define RT60_DESC                   "Current RT60 estimate in seconds"
#define HPFONOFF_DESC               "High-pass Filter on microphone signals.\n0 = OFF\n1 = ON - 70 Hz cut-off\n2 = ON - 125 Hz cut-off\n3 = ON - 180 Hz cut-off"
#define RT60ONOFF_DESC              "RT60 Estimation for AES. 0 = OFF 1 = ON"
#define AECSILENCELEVEL_DESC        "Threshold for signal detection in AEC [-inf .. 0] dBov (Default: -80dBov = 10log10(1x10-8))"
#define AECSILENCEMODE_DESC         "AEC far-end silence detection status. \n0 = false (signal detected) \n1 = true (silence detected)"
#define AECPROFILNGONOFF_DESC       "Profiling mode option. \n0 = Normal operating mode \n1 = Profiling mode (maximize CPU load)"

#define AGCONOFF_DESC               "Automatic Gain Control. \n0 = OFF \n1 = ON"
#define AGCMAXGAIN_DESC             "Maximum AGC gain factor. \n[0 .. 60] dB (default 30dB = 20log10(31.6))"
#define AGCDESIREDLEVEL_DESC        "Target power level of the output signal. \n[−inf .. 0] dBov (default: −23dBov = 10log10(0.005))"
#define AGCGAIN_DESC                "Current AGC gain factor. \n[0 .. 60] dB (default: 0.0dB = 20log10(1.0))"
#define AGCTIME_DESC                "Ramps-up / down time-constant in seconds."
#define CNIONOFF_DESC               "Comfort Noise Insertion.\n0 = OFF\n1 = ON"
#define FREEZEONOFF_DESC            "Adaptive beamformer updates.\n0 = Adaptation enabled\n1 = Freeze adaptation, filter only"
#define STATNOISEONOFF_DESC         "Stationary noise suppression.\n0 = OFF\n1 = ON"
#define GAMMA_NS_DESC               "Over-subtraction factor of stationary noise. min .. max attenuation"
#define MIN_NS_DESC                 "Gain-floor for stationary noise suppression.\n[−inf .. 0] dB (default: −16dB = 20log10(0.15))"
#define NONSTATNOISEONOFF_DESC      "Non-stationary noise suppression.\n0 = OFF\n1 = ON"
#define GAMMA_NN_DESC               "Over-subtraction factor of non- stationary noise. min .. max attenuation"
#define MIN_NN_DESC                 "Gain-floor for non-stationary noise suppression.\n[−inf .. 0] dB (default: −10dB = 20log10(0.3))"
#define ECHOONOFF_DESC              "Echo suppression.\n0 = OFF\n1 = ON"
#define GAMMA_E_DESC                "Over-subtraction factor of echo (direct and early components). min .. max attenuation"
#define GAMMA_ETAIL_DESC            "Over-subtraction factor of echo (tail components). min .. max attenuation"
#define GAMMA_ENL_DESC              "Over-subtraction factor of non-linear echo. min .. max attenuation"
#define NLATTENONOFF_DESC           "Non-Linear echo attenuation.\n0 = OFF\n1 = ON"
#define NLAEC_MODE_DESC             "Non-Linear AEC training mode.\n0 = OFF\n1 = ON - phase 1\n2 = ON - phase 2"
#define FSBUPDATE_DESC              "FSB Update Decision.\n0 = false (FSB was not updated)\n1 = true (FSB was updated)"
#define FSBPATHCHANGE_DESC          "FSB Path Change Detection.\n0 = false (no path change detected)\n1 = true (path change detected)"
#define SPEECHDETECTED_DESC         "Speech detection status.\n0 = false (no speech detected)\n1 = true (speech detected)"
#define TRANSIENTONOFF_DESC         "Transient echo suppression.\n0 = OFF\n1 = ON"
#define VOICEACTIVITY_DESC          "VAD voice activity status.\n0 = false (no voice activity)\n1 = true (voice activity)"
#define NONSTATNOISEONOFF_SR_DESC   "Non-stationary noise suppression for ASR.\n0 = OFF\n1 = ON"
#define STATNOISEONOFF_SR_DESC      "Stationary noise suppression for ASR.\n0 = OFF\n1 = ON"
#define GAMMA_NS_SR_DESC            "Over-subtraction factor of stationary noise for ASR. \n[0.0 .. 3.0] (default: 1.0)"
#define GAMMA_NN_SR_DESC            "Over-subtraction factor of non-stationary noise for ASR. \n[0.0 .. 3.0] (default: 1.1)"
#define MIN_NS_SR_DESC              "Gain-floor for stationary noise suppression for ASR.\n[−inf .. 0] dB (default: −16dB = 20log10(0.15))"
#define MIN_NN_SR_DESC              "Gain-floor for non-stationary noise suppression for ASR.\n[−inf .. 0] dB (default: −10dB = 20log10(0.3))"
#define GAMMAVAD_SR_DESC            "Set the threshold for voice activity detection.\n[−inf .. 60] dB (default: 3.5dB 20log10(1.5))"

//SRTVBF only descriptions
#define MAX_RT60_DESC               "Set the upper limit for the revest T60 estimator in seconds."
#define AECERLMAX_DESC              "Max ERL estimate."
#define BEAMWIDTH_DESC              "Width of the beam for desired speech sources. \n[23 .. 180] (default: 60 = sin−1(0.5) 360/ pi)"
#define BEAMANGLE_DESC              "Center of the beam for desired speech sources. \n[−90 .. 90] (default: 0 = sin−1(0.0) 360/2pi)"
#define SPTHRESH_DESC               "Set parameter value for DNNS."
#define ABSQFLOOR_DESC              "Absolute noise floor for voice activity detection. \n[−inf .. 60dB] (default: −infdB = 20log10(0.0))"
#define FSBUPDATED_DESC             "FSB Update Decision.\n0 = false (FSB was not updated)\n1 = true (FSB was updated)"
#define FSBFREEZEONOFF_DESC         "Adaptive beamformer updates.\n0 = Adaptation enabled\n1 = Freeze adaptation, filter only"
#define XNLTRAINONOFF_DESC          "non-linear matrix training.\n0 = OFF\n1 = ON"

#define KEYWORDDETECT_DESC          "Keyword detected. Current value so needs polling."
#define DOAANGLE_DESC               "DOA angle. Current value. Orientation depends on build configuration."

// tuning commands
#define PRINTALL_DESC               "Print all the parameters and tuning information"
#define NLMODEL_DESC                "Coefficients of the Non-Linear Echo Suppression model"
#define AECFILTER_DESC              "Coefficients of the AEC filter for a specific  mic. \nIt needs one extra input parameter for the mic index, ex: AECFILTER 0"

#if FAR_END_DSP
#define FAR_END_EQ_ONOFF_DESC       "Enable or disable equalizer for far end output signal.\n0 = OFF\n1 = ON"
#endif
